/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    tags: Tag;
    productCategories: ProductCategory;
    eventCategories: EventCategory;
    careerCategories: CareerCategory;
    partnerCategories: PartnerCategory;
    serviceCategories: ServiceCategory;
    pages: Page;
    posts: Post;
    events: Event;
    'event-registrations': EventRegistration;
    products: Product;
    services: Service;
    careers: Career;
    partners: Partner;
    companyValues: CompanyValue;
    partnerBenefits: PartnerBenefit;
    partnerTestimonials: PartnerTestimonial;
    contactLocations: ContactLocation;
    contactSubmissions: ContactSubmission;
    careerApplications: CareerApplication;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    productCategories: ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    eventCategories: EventCategoriesSelect<false> | EventCategoriesSelect<true>;
    careerCategories: CareerCategoriesSelect<false> | CareerCategoriesSelect<true>;
    partnerCategories: PartnerCategoriesSelect<false> | PartnerCategoriesSelect<true>;
    serviceCategories: ServiceCategoriesSelect<false> | ServiceCategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    companyValues: CompanyValuesSelect<false> | CompanyValuesSelect<true>;
    partnerBenefits: PartnerBenefitsSelect<false> | PartnerBenefitsSelect<true>;
    partnerTestimonials: PartnerTestimonialsSelect<false> | PartnerTestimonialsSelect<true>;
    contactLocations: ContactLocationsSelect<false> | ContactLocationsSelect<true>;
    contactSubmissions: ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    careerApplications: CareerApplicationsSelect<false> | CareerApplicationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('hy' | 'en' | 'ru') | ('hy' | 'en' | 'ru')[];
  globals: {
    header: Header;
    footer: Footer;
    siteTranslations: SiteTranslation;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteTranslations: SiteTranslationsSelect<false> | SiteTranslationsSelect<true>;
  };
  locale: 'hy' | 'en' | 'ru';
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (string | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: string;
  name: string;
  folder?: (string | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: string | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: string | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories".
 */
export interface ProductCategory {
  id: string;
  title: string;
  /**
   * Short description shown on category cards.
   */
  description?: string | null;
  image?: (string | null) | Media;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventCategories".
 */
export interface EventCategory {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careerCategories".
 */
export interface CareerCategory {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerCategories".
 */
export interface PartnerCategory {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "serviceCategories".
 */
export interface ServiceCategory {
  id: string;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'homeHero' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    /**
     * Full-width background image for the hero section.
     */
    backgroundImage?: (string | null) | Media;
    title?: string | null;
    slogan?: string | null;
    /**
     * Bullet-point features shown below the slogan.
     */
    features?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null)
              | ({
                  relationTo: 'products';
                  value: string | Product;
                } | null)
              | ({
                  relationTo: 'productCategories';
                  value: string | ProductCategory;
                } | null)
              | ({
                  relationTo: 'careers';
                  value: string | Career;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | ArticleBlock
    | HeroSliderBlock
    | PageHeroBlock
    | ValuesBlock
    | CultureBlock
    | WhatWeOfferBlock
    | FinancialReportingBlock
    | CorporateBondsBlock
    | WhyWorkBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  /**
   * Short summary shown on listing/cards.
   */
  excerpt?: string | null;
  /**
   * Build the article body using content blocks.
   */
  layout?:
    | (
        | ArticleBlock
        | ValuesBlock
        | CultureBlock
        | WhatWeOfferBlock
        | FinancialReportingBlock
        | CorporateBondsBlock
        | PageHeroBlock
        | WhyWorkBlock
      )[]
    | null;
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  tags?: (string | Tag)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleBlock".
 */
export interface ArticleBlock {
  title?: string | null;
  titleType?: ('h1' | 'h2' | 'h3') | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  imageAlignment?: ('left' | 'right') | null;
  imageColPercent?: ('25' | '33' | '40' | '50') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'articleBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesBlock".
 */
export interface ValuesBlock {
  heading?: string | null;
  subheading?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'valuesBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CultureBlock".
 */
export interface CultureBlock {
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cultureBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhatWeOfferBlock".
 */
export interface WhatWeOfferBlock {
  heading?: string | null;
  subheading?: string | null;
  categories?:
    | {
        title: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whatWeOfferBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FinancialReportingBlock".
 */
export interface FinancialReportingBlock {
  heading?: string | null;
  subheading?: string | null;
  annualReports?:
    | {
        year: string;
        file: string | Media;
        id?: string | null;
      }[]
    | null;
  quarterlyResults?:
    | {
        quarter: string;
        file?: (string | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  investorRelations?: {
    text?: string | null;
    url?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'financialReportingBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CorporateBondsBlock".
 */
export interface CorporateBondsBlock {
  heading?: string | null;
  subheading?: string | null;
  productName?: string | null;
  /**
   * e.g. "Annual Interest Rate" / "4.5%"
   */
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'corporateBondsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock".
 */
export interface PageHeroBlock {
  title: string;
  subtitle?: string | null;
  /**
   * Optional additional paragraph below the subtitle.
   */
  description?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageHeroBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyWorkBlock".
 */
export interface WhyWorkBlock {
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        icon?: ('lightning' | 'globe' | 'people' | 'star' | 'leaf' | 'chart' | 'shield' | 'heart') | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'whyWorkBlock';
}
/**
 * Product catalog entries. Not a shop — no pricing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  /**
   * One-line summary shown on catalog cards.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * First image is used as the main thumbnail on listing cards.
   */
  images?:
    | {
        image: string | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Bullet-point highlights shown on the detail page.
   */
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Technical spec table (e.g. "Package sizes" / "1 kg, 5 kg, 20 kg").
   */
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Datasheets, brochures, safety sheets etc.
   */
  documents?:
    | {
        /**
         * e.g. "Product Datasheet" or "Safety Data Sheet"
         */
        label: string;
        file: string | Media;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  status?: ('active' | 'coming-soon' | 'discontinued') | null;
  /**
   * Highlighted on the category listing.
   */
  featured?: boolean | null;
  categories?: (string | ProductCategory)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: string;
  title: string;
  department?: string | null;
  location?: string | null;
  /**
   * e.g., Full-time, Part-time
   */
  type?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  categories?: (string | CareerCategory)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSliderBlock".
 */
export interface HeroSliderBlock {
  /**
   * Add 1–5 slides. Each slide shares the same layout as the home hero.
   */
  slides?:
    | {
        /**
         * Full-width background image for this slide.
         */
        backgroundImage?: (string | null) | Media;
        title?: string | null;
        slogan?: string | null;
        /**
         * Bullet-point features shown below the slogan.
         */
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null)
                  | ({
                      relationTo: 'products';
                      value: string | Product;
                    } | null)
                  | ({
                      relationTo: 'productCategories';
                      value: string | ProductCategory;
                    } | null)
                  | ({
                      relationTo: 'careers';
                      value: string | Career;
                    } | null);
                url?: string | null;
                label: string;
                /**
                 * Choose how the link should be rendered.
                 */
                appearance?: ('default' | 'outline') | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Automatically advance slides every 5 seconds.
   */
  autoplay?: boolean | null;
  /**
   * Milliseconds between slide transitions.
   */
  autoplayInterval?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroSliderBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  title: string;
  date: string;
  location: string;
  image?: (string | null) | Media;
  /**
   * A short description shown on the events list page.
   */
  description: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  categories?: (string | EventCategory)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  event: string | Event;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  description: string;
  /**
   * Provide the raw SVG string for the icon
   */
  iconSvg: string;
  categories?: (string | ServiceCategory)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: string;
  /**
   * The name of the partner
   */
  title: string;
  logo: string | Media;
  description?: string | null;
  websiteUrl?: string | null;
  categories?: (string | PartnerCategory)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Core values displayed on the About Us page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyValues".
 */
export interface CompanyValue {
  id: string;
  title: string;
  description?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Benefit cards displayed on the Partners page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerBenefits".
 */
export interface PartnerBenefit {
  id: string;
  title: string;
  description?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Testimonial quotes displayed on the Partners page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerTestimonials".
 */
export interface PartnerTestimonial {
  id: string;
  quote: string;
  authorName: string;
  /**
   * e.g. "CEO, Asia Pacific Agri"
   */
  authorTitle?: string | null;
  partner?: (string | null) | Partner;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Office and department contact cards displayed on the Contacts page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactLocations".
 */
export interface ContactLocation {
  id: string;
  /**
   * e.g. "Main Office & Showroom" or "Sales Department"
   */
  name: string;
  /**
   * Determines which section on the Contacts page this card appears in.
   */
  type: 'office' | 'department';
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  address?: string | null;
  phones?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  email?: string | null;
  /**
   * Link to Google Maps for the "View on Map" button.
   */
  mapUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages submitted through the Contact Us form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions".
 */
export interface ContactSubmission {
  id: string;
  firstName: string;
  lastName?: string | null;
  email: string;
  phone?: string | null;
  company?: string | null;
  subject?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Applications submitted via the Apply Now form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careerApplications".
 */
export interface CareerApplication {
  id: string;
  career?: (string | null) | Career;
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'productCategories';
        value: string | ProductCategory;
      } | null)
    | ({
        relationTo: 'eventCategories';
        value: string | EventCategory;
      } | null)
    | ({
        relationTo: 'careerCategories';
        value: string | CareerCategory;
      } | null)
    | ({
        relationTo: 'partnerCategories';
        value: string | PartnerCategory;
      } | null)
    | ({
        relationTo: 'serviceCategories';
        value: string | ServiceCategory;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: string | EventRegistration;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'careers';
        value: string | Career;
      } | null)
    | ({
        relationTo: 'partners';
        value: string | Partner;
      } | null)
    | ({
        relationTo: 'companyValues';
        value: string | CompanyValue;
      } | null)
    | ({
        relationTo: 'partnerBenefits';
        value: string | PartnerBenefit;
      } | null)
    | ({
        relationTo: 'partnerTestimonials';
        value: string | PartnerTestimonial;
      } | null)
    | ({
        relationTo: 'contactLocations';
        value: string | ContactLocation;
      } | null)
    | ({
        relationTo: 'contactSubmissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'careerApplications';
        value: string | CareerApplication;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: string | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventCategories_select".
 */
export interface EventCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careerCategories_select".
 */
export interface CareerCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerCategories_select".
 */
export interface PartnerCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "serviceCategories_select".
 */
export interface ServiceCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        backgroundImage?: T;
        title?: T;
        slogan?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        articleBlock?: T | ArticleBlockSelect<T>;
        heroSliderBlock?: T | HeroSliderBlockSelect<T>;
        pageHeroBlock?: T | PageHeroBlockSelect<T>;
        valuesBlock?: T | ValuesBlockSelect<T>;
        cultureBlock?: T | CultureBlockSelect<T>;
        whatWeOfferBlock?: T | WhatWeOfferBlockSelect<T>;
        financialReportingBlock?: T | FinancialReportingBlockSelect<T>;
        corporateBondsBlock?: T | CorporateBondsBlockSelect<T>;
        whyWorkBlock?: T | WhyWorkBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleBlock_select".
 */
export interface ArticleBlockSelect<T extends boolean = true> {
  title?: T;
  titleType?: T;
  content?: T;
  image?: T;
  imageAlignment?: T;
  imageColPercent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSliderBlock_select".
 */
export interface HeroSliderBlockSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        backgroundImage?: T;
        title?: T;
        slogan?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  autoplay?: T;
  autoplayInterval?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageHeroBlock_select".
 */
export interface PageHeroBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ValuesBlock_select".
 */
export interface ValuesBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CultureBlock_select".
 */
export interface CultureBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhatWeOfferBlock_select".
 */
export interface WhatWeOfferBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  categories?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FinancialReportingBlock_select".
 */
export interface FinancialReportingBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  annualReports?:
    | T
    | {
        year?: T;
        file?: T;
        id?: T;
      };
  quarterlyResults?:
    | T
    | {
        quarter?: T;
        file?: T;
        url?: T;
        id?: T;
      };
  investorRelations?:
    | T
    | {
        text?: T;
        url?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CorporateBondsBlock_select".
 */
export interface CorporateBondsBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  productName?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WhyWorkBlock_select".
 */
export interface WhyWorkBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  items?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        articleBlock?: T | ArticleBlockSelect<T>;
        valuesBlock?: T | ValuesBlockSelect<T>;
        cultureBlock?: T | CultureBlockSelect<T>;
        whatWeOfferBlock?: T | WhatWeOfferBlockSelect<T>;
        financialReportingBlock?: T | FinancialReportingBlockSelect<T>;
        corporateBondsBlock?: T | CorporateBondsBlockSelect<T>;
        pageHeroBlock?: T | PageHeroBlockSelect<T>;
        whyWorkBlock?: T | WhyWorkBlockSelect<T>;
      };
  relatedPosts?: T;
  categories?: T;
  tags?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  location?: T;
  image?: T;
  description?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  event?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  status?: T;
  featured?: T;
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  iconSvg?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  type?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  title?: T;
  logo?: T;
  description?: T;
  websiteUrl?: T;
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companyValues_select".
 */
export interface CompanyValuesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerBenefits_select".
 */
export interface PartnerBenefitsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerTestimonials_select".
 */
export interface PartnerTestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorTitle?: T;
  partner?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactLocations_select".
 */
export interface ContactLocationsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  order?: T;
  address?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  email?: T;
  mapUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactSubmissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careerApplications_select".
 */
export interface CareerApplicationsSelect<T extends boolean = true> {
  career?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null)
            | ({
                relationTo: 'products';
                value: string | Product;
              } | null)
            | ({
                relationTo: 'productCategories';
                value: string | ProductCategory;
              } | null)
            | ({
                relationTo: 'careers';
                value: string | Career;
              } | null);
          url?: string | null;
          label: string;
        };
        /**
         * Optional sub-links shown in a dropdown under this item.
         */
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null)
                  | ({
                      relationTo: 'products';
                      value: string | Product;
                    } | null)
                  | ({
                      relationTo: 'productCategories';
                      value: string | ProductCategory;
                    } | null)
                  | ({
                      relationTo: 'careers';
                      value: string | Career;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  companyName?: string | null;
  companyTagline?: string | null;
  contact?: {
    columnLabel?: string | null;
    address?: string | null;
    phone?: string | null;
    email?: string | null;
  };
  /**
   * Up to 2 link columns shown in the footer.
   */
  navColumns?:
    | {
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: string | Post;
                    } | null)
                  | ({
                      relationTo: 'products';
                      value: string | Product;
                    } | null)
                  | ({
                      relationTo: 'productCategories';
                      value: string | ProductCategory;
                    } | null)
                  | ({
                      relationTo: 'careers';
                      value: string | Career;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown in the footer and on the Contacts page.
   */
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'twitter' | 'telegram' | 'whatsapp';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The current year and © symbol are added automatically. Only edit the text after the year.
   */
  copyrightSuffix?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Editable UI strings for all pages (buttons, labels, messages).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteTranslations".
 */
export interface SiteTranslation {
  id: string;
  events?: {
    upcomingTitle?: string | null;
    pastTitle?: string | null;
    noUpcoming?: string | null;
    noPast?: string | null;
    registerNow?: string | null;
    viewHighlights?: string | null;
    eventLabel?: string | null;
    allEvents?: string | null;
    upcoming?: string | null;
    past?: string | null;
    allCategories?: string | null;
    registrationClosed?: string | null;
    registrationClosedMsg?: string | null;
    registerTitle?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    emailLabel?: string | null;
    phoneLabel?: string | null;
    registering?: string | null;
    registerSuccess?: string | null;
    registerError?: string | null;
    backToEvents?: string | null;
    noResults?: string | null;
  };
  careers?: {
    openPositions?: string | null;
    allCategories?: string | null;
    viewPosition?: string | null;
    noPositions?: string | null;
    back?: string | null;
    applyTitle?: string | null;
    applyName?: string | null;
    applyEmail?: string | null;
    applyPhone?: string | null;
    applyMessage?: string | null;
    applySubmit?: string | null;
    applySending?: string | null;
    applySuccess?: string | null;
    applyError?: string | null;
  };
  contacts?: {
    infoTitle?: string | null;
    desc?: string | null;
    addressTitle?: string | null;
    callUs?: string | null;
    emailUs?: string | null;
    viewMap?: string | null;
    formTitle?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    emailLabel?: string | null;
    phoneLabel?: string | null;
    company?: string | null;
    subject?: string | null;
    message?: string | null;
    send?: string | null;
    officesTitle?: string | null;
    departmentsTitle?: string | null;
    viewOnMap?: string | null;
    followUs?: string | null;
    website?: string | null;
    sending?: string | null;
    successMsg?: string | null;
    errorMsg?: string | null;
    /**
     * Value is used for form processing — keep it lowercase, no spaces. Label is what users see.
     */
    subjectOptions?:
      | {
          /**
           * e.g. "general", "partnership"
           */
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  partners?: {
    growingTitle?: string | null;
    growingSub1?: string | null;
    growingSub2?: string | null;
    strategicTitle?: string | null;
    strategicSub?: string | null;
    otherPartners?: string | null;
    benefitsTitle?: string | null;
    benefitsSub?: string | null;
    becomeTitle?: string | null;
    becomeText?: string | null;
    contactBtn?: string | null;
    testimonialsTitle?: string | null;
    visitWebsite?: string | null;
    noPartners?: string | null;
  };
  financialReporting?: {
    annualReports?: string | null;
    quarterlyResults?: string | null;
    download?: string | null;
    view?: string | null;
  };
  blog?: {
    pageTitle?: string | null;
    allCategories?: string | null;
    allTags?: string | null;
    readMore?: string | null;
    noPosts?: string | null;
    backToBlog?: string | null;
    tags?: string | null;
    relatedPosts?: string | null;
    searchPlaceholder?: string | null;
  };
  products?: {
    allCategories?: string | null;
    viewProducts?: string | null;
    contactBtn?: string | null;
    noProducts?: string | null;
    viewDetails?: string | null;
    featured?: string | null;
    comingSoon?: string | null;
    discontinued?: string | null;
    featuresHeading?: string | null;
    specsHeading?: string | null;
    documentsHeading?: string | null;
    download?: string | null;
    inquire?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  companyName?: T;
  companyTagline?: T;
  contact?:
    | T
    | {
        columnLabel?: T;
        address?: T;
        phone?: T;
        email?: T;
      };
  navColumns?:
    | T
    | {
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyrightSuffix?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteTranslations_select".
 */
export interface SiteTranslationsSelect<T extends boolean = true> {
  events?:
    | T
    | {
        upcomingTitle?: T;
        pastTitle?: T;
        noUpcoming?: T;
        noPast?: T;
        registerNow?: T;
        viewHighlights?: T;
        eventLabel?: T;
        allEvents?: T;
        upcoming?: T;
        past?: T;
        allCategories?: T;
        registrationClosed?: T;
        registrationClosedMsg?: T;
        registerTitle?: T;
        firstName?: T;
        lastName?: T;
        emailLabel?: T;
        phoneLabel?: T;
        registering?: T;
        registerSuccess?: T;
        registerError?: T;
        backToEvents?: T;
        noResults?: T;
      };
  careers?:
    | T
    | {
        openPositions?: T;
        allCategories?: T;
        viewPosition?: T;
        noPositions?: T;
        back?: T;
        applyTitle?: T;
        applyName?: T;
        applyEmail?: T;
        applyPhone?: T;
        applyMessage?: T;
        applySubmit?: T;
        applySending?: T;
        applySuccess?: T;
        applyError?: T;
      };
  contacts?:
    | T
    | {
        infoTitle?: T;
        desc?: T;
        addressTitle?: T;
        callUs?: T;
        emailUs?: T;
        viewMap?: T;
        formTitle?: T;
        firstName?: T;
        lastName?: T;
        emailLabel?: T;
        phoneLabel?: T;
        company?: T;
        subject?: T;
        message?: T;
        send?: T;
        officesTitle?: T;
        departmentsTitle?: T;
        viewOnMap?: T;
        followUs?: T;
        website?: T;
        sending?: T;
        successMsg?: T;
        errorMsg?: T;
        subjectOptions?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  partners?:
    | T
    | {
        growingTitle?: T;
        growingSub1?: T;
        growingSub2?: T;
        strategicTitle?: T;
        strategicSub?: T;
        otherPartners?: T;
        benefitsTitle?: T;
        benefitsSub?: T;
        becomeTitle?: T;
        becomeText?: T;
        contactBtn?: T;
        testimonialsTitle?: T;
        visitWebsite?: T;
        noPartners?: T;
      };
  financialReporting?:
    | T
    | {
        annualReports?: T;
        quarterlyResults?: T;
        download?: T;
        view?: T;
      };
  blog?:
    | T
    | {
        pageTitle?: T;
        allCategories?: T;
        allTags?: T;
        readMore?: T;
        noPosts?: T;
        backToBlog?: T;
        tags?: T;
        relatedPosts?: T;
        searchPlaceholder?: T;
      };
  products?:
    | T
    | {
        allCategories?: T;
        viewProducts?: T;
        contactBtn?: T;
        noProducts?: T;
        viewDetails?: T;
        featured?: T;
        comingSoon?: T;
        discontinued?: T;
        featuresHeading?: T;
        specsHeading?: T;
        documentsHeading?: T;
        download?: T;
        inquire?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}